[DEBUG] [2020-11-20 07:17:41,743] [11809:140710994700096] - pool.py[line:129]: No connection available in pool.
[DEBUG] [2020-11-20 07:17:41,759] [11809:140710994700096] - pool.py[line:158]: Created new connection 140710384429712.
[DEBUG] [2020-11-20 07:17:41,768] [11809:140710994700096] - peewee.py[line:2863]: ('SELECT `t1`.`f_create_date`, `t1`.`f_update_date`, `t1`.`f_name`, `t1`.`f_namespace`, `t1`.`f_address`, `t1`.`f_engine`, `t1`.`f_type`, `t1`.`f_options`, `t1`.`f_partitions`, `t1`.`f_id_delimiter`, `t1`.`f_in_serialized`, `t1`.`f_have_head`, `t1`.`f_schema`, `t1`.`f_count`, `t1`.`f_part_of_data`, `t1`.`f_description`, `t1`.`f_create_time`, `t1`.`f_update_time` FROM `t_storage_table_meta` AS `t1` WHERE ((`t1`.`f_name` = %s) AND (`t1`.`f_namespace` = %s))', ['66038dc82b0011ebae9d4e9ecd9d57e8', 'output_data_202011200707112994524_hetero_secure_boost_0_0'])
[DEBUG] [2020-11-20 07:17:41,778] [11809:140710994700096] - pool.py[line:185]: Returning 140710384429712 to pool.
