[DEBUG] [2020-11-20 02:37:16,641] [1888:140512266434368] - pool.py[line:129]: No connection available in pool.
[DEBUG] [2020-11-20 02:37:16,663] [1888:140512266434368] - pool.py[line:158]: Created new connection 140511984908440.
[DEBUG] [2020-11-20 02:37:16,680] [1888:140512266434368] - peewee.py[line:2863]: ('SELECT `t1`.`f_create_date`, `t1`.`f_update_date`, `t1`.`f_name`, `t1`.`f_namespace`, `t1`.`f_address`, `t1`.`f_engine`, `t1`.`f_type`, `t1`.`f_options`, `t1`.`f_partitions`, `t1`.`f_id_delimiter`, `t1`.`f_in_serialized`, `t1`.`f_have_head`, `t1`.`f_schema`, `t1`.`f_count`, `t1`.`f_part_of_data`, `t1`.`f_description`, `t1`.`f_create_time`, `t1`.`f_update_time` FROM `t_storage_table_meta` AS `t1` WHERE ((`t1`.`f_name` = %s) AND (`t1`.`f_namespace` = %s))', ['330a67742ad911eb94f93ea3df35c0a6', 'output_data_202011200231350021282_hetero_feature_selection_0_0'])
[DEBUG] [2020-11-20 02:37:16,708] [1888:140512266434368] - pool.py[line:185]: Returning 140511984908440 to pool.
